// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdasoHxAn2rjoVpU80HeDXCBWfhzf5n_s',
    appId: '1:767892366272:web:4e6266c1144762d1a7de25',
    messagingSenderId: '767892366272',
    projectId: 'test-75600',
    authDomain: 'test-75600.firebaseapp.com',
    databaseURL: 'https://test-75600-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-75600.appspot.com',
    measurementId: 'G-9EW58ZPYJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfu4daDI33kvw_MlqZ6bCbxRdXISiDlQk',
    appId: '1:767892366272:android:7eadb9c75af38fb7a7de25',
    messagingSenderId: '767892366272',
    projectId: 'test-75600',
    databaseURL: 'https://test-75600-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-75600.appspot.com',
  );
}
